FROM node:lts-alpine
COPY --from=venti:base2 /app/venti /app/
WORKDIR /temp/
COPY . ./
RUN cd web && npm install --force
RUN cd web && npm run build
RUN mkdir -p             /app/web/
RUN cp -a /temp/web/dist /app/web/
RUN cp -a ./tools        /app/
RUN mkdir -p             /app/data
